### ISSUE TITLE
Permissions issue

### ISSUE THREAD

**Issue by tonifisler** [antistatique/antistatique.net#321] opened 2016-01-26 17:23 UTC
While logged in with my account, I noticed issues when saving a basic page created by someone else. No HTML changes are effective. I guess this is a permission problem.

**Comment by Sudei** [comment] 2016-08-05 06:38
I can't reproduce the bug.

I try with basic pages // articles using multiple CKeditor options such : 
- Full HTML
- Filtred HTML
- Markdown

Should we wait or close this issue ?

**Closed** 2016-11-28 12:33 UTC
