### ISSUE TITLE
Blog : wrong url

### ISSUE THREAD

**Issue by nsz** [antistatique/antistatique.net#169] opened 2015-05-18 11:23 UTC
### What we have
Sometimes, articles have links that refer to articles or content of the old website

### What we want
Links of the new website 

Is it possible to automate this task ?

**Comment by gido** [comment] 2015-05-18 14:27
We will add redirection based on the Spreadsheet document

**Comment by tonifisler** [comment] 2015-05-22 14:59
Duplicate of #104

**Closed by tonifisler** 2015-05-22 14:59 UTC
Labels: bug
